### ISSUE TITLE
Incompatible Type Errors

### ISSUE THREAD

**Issue by SentToDevNull** [maK-/maK_it-Linux-Rootkit#2]
maK_it.c:74:44: error: incompatible types when assigning to type ‘kgid_t {aka struct <anonymous>}’ from type ‘int’
  haxcredentials->uid = haxcredentials->gid = 0;

**Comment by maK-** [comment]
Thanks for correcting my 3 year old college work, this project might really take off!

**Comment by SentToDevNull** [comment]
My pleasure.
